### ISSUE TITLE
Wki pages or GH pages - Split readme & generate documentation

### ISSUE THREAD

**Issue by rosepearson** [rosepearson/GeoFabrics#20]
The readme is getting increasingly long as some sections can be separated out into separate pages.

**Comment by kinow** [comment]
Or maybe consider using GH pages, and generating the documentation with Sphinx? This has the advantage that you can generate parts of the docs from the code (or use code in the docs), which will break if you change the code and forget updating the docs... this helps us in Cylc to force developers to maintain the code & docs both up to date :sweat_smile: 

PR's can also automatically build the docs and tell contributors they have broken the docs. Sphinx does require some fiddling since it's not as simple as just Markdown or text though.

There should be no costs for this, and you just need to enable GH Pages. The page would be available at http://rosepearson.github.io/GeoFabrics, or you can have another domain redirecting to this URL.

**Comment by rosepearson** [comment]
Thanks @kinow - that's a great suggestion!

**Comment by rosepearson** [comment]
Cool - I've updated GeoFabrics to support pages. I've not yet incorporated anything built from doc-strings using Sphinx. I'm going to close this issues as the initial goal of splitting out the readme into multiple pages. I'll start using Spinx to generate pages either as part of other issues (i.e. the 'updating documentation' check-box) or in another issue dedicated to documentation.

**Comment by rosepearson** [comment]
Cool. Thanks @kinow - I've updated GeoFabrics to support pages, but I've not yet incorporated anything built from doc-strings using Sphinx. 

I'm going to close this issues as the initial goal of splitting out the readme into multiple pages. I'll start using Spinx to generate pages either as part of other issues (i.e. the 'updating documentation' check-box) or in another issue dedicated to documentation.
